language: cpp
compiler: 
  - gcc
sudo: required
dist: trusty

script:
    - ./install.sh --fast &>/dev/null
    - ./bin/parsecmgmt -a build -p parsec -c gcc-ff &>./log.txt
    - tail -100 log.txt
    - ./bin/parsecmgmt -a build -p parsec -c gcc-skepu &>./log.txt
    - tail -100 log.txt
    - ./bin/parsecmgmt -a build -p parsec -c gcc-pthreads &>./log.txt
    - tail -100 log.txt
    - ./bin/parsecmgmt -a build -p parsec -c gcc-openmp &>./log.txt
    - tail -100 log.txt
    - ./bin/parsecmgmt -a build -p parsec -c gcc-tbb &>./log.txt
    - tail -100 log.txt
    - ./bin/parsecmgmt -a build -p parsec -c gcc-serial &>./log.txt
    - tail -100 log.txt

notifications:
  email:
    recipients:
      - d.desensi.software@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  
